### ISSUE TITLE
curl issue "BN_r and_range:too many iterations"

### ISSUE THREAD

**Issue by evsc** [bakercp/ofxSMTP#10]
I'm running into an issue with curl that is not the addon's fault, but I thought I'd post it here in case you/someone has experienced this before.

Getting these errors:
```
[ error ] Client::threadedFunction: SSL Exception : SSL Exception: error:0307A07
1:bignum routines:BN_rand_range:too many iterations
[ error ] ofApp::onSMTPException: Exception: error:0307A071:bignum routines:BN_r
and_range:too many iterations
[ error ] Client::threadedFunction: SSL Exception : SSL Exception: error:0307A07
1:bignum routines:BN_rand_range:too many iterations
[ error ] ofApp::onSMTPException: Exception: error:0307A071:bignum routines:BN_r
and_range:too many iterations
```

Which led me here https://github.com/mitchellh/vagrant/issues/5016 where people fixed the issue by replacing a curl.exe. The only curl.exe I found on my system is part of my Git install. Though replacing that one didn't do anything. More likely that the issue is with my MinGW install? 

Windows 8.1
of_v0.8.4_win_cb_release
codeblocks-12.11mingw

**Comment by bakercp** [comment]
This is very odd because this add-on does not use CURL.  But this add-on,
like CURL does use openssl ... Does this always happen or only with
particular servers?

**Comment by evsc** [comment]
Only had tried it with gmail so far. But I had the same code working on another w8.1 machine, so I just figured it had to do with the local libraries.

**Comment by bakercp** [comment]
I'm going to close this because curl is not used in this addon.
