### ISSUE TITLE
tr1/memory file not found

### ISSUE THREAD

**Issue by Meach** [bakercp/ofxSMTP#11]
Hi,

I just tried to use the addon with OF 0.9.0 and got this tr1 memory error:

```
ofxSMTP/libs/ofxSMTP/include/ofx/SMTP/Types.h:32: error: 'tr1/memory' file not found
#include <tr1/memory>
```

I couldn't find a solution to this, tried both with Xcode and QtCreator and result was the same. Any hint why I get this? (I thought this recurring error was fixed in OF itself already).

Thanks

**Comment by bakercp** [comment]
I just pushed my 0.9.0 branch to master.  Can you give it a try and close the issue if it's fixed?

**Comment by Meach** [comment]
It's now working fine!
