### ISSUE TITLE
Gmail security settings appear to be blocking connection

### ISSUE THREAD

**Issue by robzach** [bakercp/ofxSMTP#13]
Ran example-basic-gmail built in OF 0.9.3, but got this console message when trying to send an email:

```
[ error ] ofApp::onSMTPException: Exception: Login using LOGIN password failed: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/answer/14257 j88sm1532869qgf.7 - gsmtp
```

This same error appears whether the password provided is correct or incorrect. (The alphanumeric string is, however, unique to each request.)

Gmail allows users to permit access for "less secure apps" (available at https://www.google.com/settings/security/lesssecureapps) but even turning this option on does not fix the issue.

**Comment by bakercp** [comment]
In addition to letting "less secure" apps log in (sounds like you did it already) ...
- Generate an app-specific password: https://support.google.com/accounts/answer/185833?hl=en
- Use `ofx::SMTP::GmailSettings settings("YOU@GMAIL.COM","APP_SPECIFIC_PASSWORD");

Works for me.

**Comment by bakercp** [comment]
Or, if you don't want to use `ofx::SMTP::GmailSettings` just use the normal settings with a config file like:

```
<account>
    <host>smtp.gmail.com</host>
    <port>587</port>
    <encryption>STARTTLS</encryption>
    <timeout>30000</timeout>
    <message-send-delay>100</message-send-delay>
    <authentication>
        <username>YOU@GMAIL.COM</username>
        <password>APP_SPECIFIC_PASSWORD</password>
        <type>AUTH_LOGIN</type>
    </authentication>
</account>
```

**Comment by robzach** [comment]
Sorry about the crazy long lag time here. Put the project down and am now picking it back up.

As per your suggestion I generated an app-specific password and it worked without any trouble.

Thanks!
