### ISSUE TITLE
Problems embedding photos in a mail

### ISSUE THREAD

**Issue by rjx-ray** [bakercp/ofxSMTP#16]
I have a requirement to send emails with  embedded photos.
I'm using a html template email with a  img tag inside it like this
```C++
<img src = "cid:image1">
```
I'm loading the template into a string then adding it to the mail, then adding the image file part

```C++
	using namespace Poco::Net;

	// create and initiliase a multipart html email
	auto message = std::make_shared<Poco::Net::MailMessage>();
	Poco::Net::MediaType mediaType("multipart", "related");
	mediaType.setParameter("type", "text/html");
	message->setContentType(mediaType);

	// add the previously loaded html part
	message->addPart("", new Poco::Net::StringPartSource(mailTextHtml, "text/html"), MailMessage::CONTENT_INLINE, MailMessage::ENCODING_QUOTED_PRINTABLE);

	// get the image, tag it, and add it to the message
	Poco::Net::FilePartSource *image = new Poco::Net::FilePartSource(ofToDataPath(imageFilePathName));
	image->headers().add("Content-ID", "<image1>");   // assumes there is an image tag in the HTML for <image1>
	message->addPart("", image, MailMessage::CONTENT_INLINE, MailMessage::ENCODING_BASE64);

	// Encode the sender and set it.
	message->setSender(Poco::Net::MailMessage::encodeWord(senderEMail, "UTF-8"));
```
This is working OK for some mail clients (outlook, gmail) but not for others (ios, thunderbird) where the image comes through as an attachment.
Its a real problem as we want the mail to show up on both iPhone and Android with the picture in the screen.

Any ideas?

**Comment by bakercp** [comment]
Hi @rjx-ray -- unfortunately I don't have any tips for you on this.  My strategy to figure it out would be to look at the raw source of the sent emails and make sure that it matches what is needed.  Other than that, I don't know of any special functions in my code or in the underlying Poco code that will fix this.  If you find a solution, please update this thread!

Good luck!

**Comment by rjx-ray** [comment]
Hi,
Thanks for the tips
I fixed it for Thunderbird by creating the part with an image name & path, eg
`Poco::Net::FilePartSource *image = new Poco::Net::FilePartSource(ofToDataPath(imageFilePathName), "PhotoImage.jpg", "image/jpeg")`
I fixed it for iOS by also attaching the image

**Comment by bakercp** [comment]
Nice!  Thanks for reporting back.
